#!/bin/bash

# test for dependencies
if command -v zenity >/dev/null 2>&1;
then
    echo "Looking for zenity...OK.\n"
else
	echo "Looking for zenity...MISSING.\nPlease install it and restart this installer.\n"
	exit;
fi

if command -v xclip >/dev/null 2>&1;
then
    echo "Looking for xclip...OK.\n"
else
	echo "Looking for xclip...MISSING.\nPlease install it and restart this installer.\n"
	exit;
fi

if command -v curl >/dev/null 2>&1;
then
    echo "Looking for curl...OK.\n"
else
	echo "Looking for curl...MISSING.\nPlease install it and restart this installer.\n"
	exit;
fi

sleep 10

# add icon
echo "Installing owncloud icon to your homedir (/home/$(whoami)/.icons)..."
if [ ! -d "~/.icons" ]; then
  mkdir ~/.icons
fi
cp icon.png ~/.icons/

# place core bash script
echo "Installing sharing script to your homedir (/home/$(whoami)/bin)..."
if [ ! -d "~/bin" ]; then
  mkdir ~/bin
fi
cp shareLinkCreator ~/bin

## thunar specific
if [ -f /usr/bin/thunar ]
then
	echo "Thunar installed, processing custom actions file..."
	# backup original thunar actions file
	cp ~/.config/Thunar/uca.xml ~/.config/Thunar/uca.xml.sharelinkBAK

	# replace last line "</actions>"
	sed -i '$d' ~/.config/Thunar/uca.xml
	cat shareLinkCreator.thunar_action >> ~/.config/Thunar/uca.xml
	
	echo "Restarting Thunar."
	killall -9 thunar -u $(whoami)
	thunar
else
    echo "Thunar is not installed."
fi

## nemo specific
if [ -f /usr/bin/nemo ]
then
	echo "Nemo installed, copying custom action file..."
	cp shareLinkCreator.nemo.action ~/.local/share/nemo/actions/
else
    echo "Nemo is not installed."
fi
